### ISSUE TITLE
Unable to install flask-mysqldb in mac

### ISSUE THREAD

**Issue by darshanddd7** [alexferl/flask-mysqldb#12]
Darshans-MacBook-Air:CrudWithFlask-4 ddd$ pip3 install Flask-Mysqldb
Collecting Flask-Mysqldb
Using cached Flask-MySQLdb-0.2.0.tar.gz
Requirement already satisfied: Flask>=0.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Flask-Mysqldb)
Collecting mysqlclient (from Flask-Mysqldb)
Using cached mysqlclient-1.3.12.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/setup.py", line 17, in 
metadata, options = get_config()
File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/setup_posix.py", line 54, in get_config
libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/setup_posix.py", line 54, in 
libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/setup_posix.py", line 12, in dequote
if s[0] in ""'" and s[0] == s[-1]:
IndexError: string index out of range

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-ltokdkl1/mysqlclient/

**Comment by darshanddd7** [comment]
I have installed all dependencies like:
*Darshans-Air:~ ddd$ pip3 freeze
click==6.7
configparser==3.5.0
Flask==0.12.2
Flask-MySQL==1.4.0
Flask-WTF==0.14.2
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
mock==2.0.0
mysql-connector-python==2.1.7
passlib==1.7.1
pbr==4.0.0
PyMySQL==0.8.0
six==1.11.0
Werkzeug==0.14.1
WTForms==2.1

**Comment by alexferl** [comment]
It seems like a mysqlclient issue.
How did you install mysql on your Mac?
