### ISSUE TITLE
Error install the package

### ISSUE THREAD

**Issue by iCHAIT** [alexferl/flask-mysqldb#14]
I am trying to install the package for my flask app and I get the following error -

```shell
Collecting flask-mysqldb
  Using cached https://files.pythonhosted.org/packages/62/e3/955c845efe1aacf30c8e2607470544ede36aa1044f6382c809f13e014104/Flask-MySQLdb-0.2.0.tar.gz
Requirement already satisfied: Flask>=0.10 in ./env/lib/python3.5/site-packages (from flask-mysqldb) (1.0.2)
Collecting mysqlclient (from flask-mysqldb)
  Using cached https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9pf1mpmn/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-9pf1mpmn/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-9pf1mpmn/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9pf1mpmn/mysqlclient/
```

I am using a `virtual environment` and made sure that `setuptools` is installed and up to date.

Python version - `Python 3.5.2`

Can you please help me? What is possibly going wrong here?

**Comment by iCHAIT** [comment]
I found a solution - 

I hadn't installed `mysql_config` -

`sudo apt-get install libmysqlclient-dev`

The above command installed it and fixed the error for me.
