### ISSUE TITLE
Error while installing with pip

### ISSUE THREAD

**Issue by japrozs** [alexferl/flask-mysqldb#25]
I tried to install it with pip on MacOS
```bash
pip3 install flask-mysqldb
```
This is what I got in return:
```bash
$ pip3 install flask-mysqldb
Collecting flask-mysqldb
  Using cached Flask-MySQLdb-0.2.0.tar.gz (2.1 kB)
Requirement already satisfied: Flask>=0.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from flask-mysqldb) (1.1.2)
Collecting mysqlclient
  Using cached mysqlclient-2.0.1.tar.gz (87 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sf/g8jsr5hx61707p3x_l30042r0000gn/T/pip-install-lww9m60l/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/sf/g8jsr5hx61707p3x_l30042r0000gn/T/pip-install-lww9m60l/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/sf/g8jsr5hx61707p3x_l30042r0000gn/T/pip-pip-egg-info-geftj76p
         cwd: /private/var/folders/sf/g8jsr5hx61707p3x_l30042r0000gn/T/pip-install-lww9m60l/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sf/g8jsr5hx61707p3x_l30042r0000gn/T/pip-install-lww9m60l/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/private/var/folders/sf/g8jsr5hx61707p3x_l30042r0000gn/T/pip-install-lww9m60l/mysqlclient/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/sf/g8jsr5hx61707p3x_l30042r0000gn/T/pip-install-lww9m60l/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Please respond to the earliest

**Comment by HarunMbaabu** [comment]
Getting the same error 🥲🥲

**Comment by alexferl** [comment]
@japrozs @HarunMbaabu https://github.com/alexferl/flask-mysqldb/issues/22#issuecomment-653775776
